apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus
spec:
  selector:
    app: alertmanager
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    targetPort: 9093