apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: prometheus
data:
  alerting_rules.yml: |
    groups:
      - name: example
        rules:
        - alert: HighCpuUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: High CPU usage detected on {{ $labels.instance }}
            description: "{{ $labels.instance }} has a CPU usage above 80% for more than 5 minutes."