apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: windows-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app: windows-exporter
  template:
    metadata:
      labels:
        app: windows-exporter
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9182'
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: "os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"
      containers:
      - name: windows-exporter
        image: ghcr.io/prometheus-community/windows-exporter:0.24.0  # specified version
        ports:
        - containerPort: 9182
        args:
          - '--collectors.enabled=cpu,cs,disk,logical_disk,net,os,service,system,textfile,container'
          - '--telemetry.addr=:9182'